django_music_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('music.urls',namespace='music')),
    url('', include('pwa.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<filter_by>[a-zA_Z]+)/(?P<modifier>[a-zA_Z]+)/$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/(?P<modifier>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^(?P<album_id>[0-9]+)/(?P<modifier>[a-zA_Z]+)/album_modify/$', views.album_modify, name='album_modify'),
    url(r'^(?P<song_id>[0-9]+)/(?P<modifier>[a-zA_Z]+)/song_modify/$', views.song_modify, name='song_modify'),
    url(r'^(?P<song_id>[0-9]+)/(?P<album_title>[a-zA_Z]+)/move_song/$', views.move_song, name='move_song'),
    url(r'^(?P<song_id>[0-9]+)/(?P<album_title>[a-zA_Z]+)/copy_song/$', views.copy_song, name='copy_song'),
    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^add_song/$', views.add_song, name='add_song'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<album_id>[0-9]+)/(?P<song_id>[0-9]+)/delete_song/$', views.delete_song, name='delete_song'),
    url(r'^(?P<song_id>[0-9]+)/del_song/$', views.del_song, name='del_song'),
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
]

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

class Album(models.Model):

    user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(default="avatar.jpg")
    album_visibility = models.CharField(max_length=100, default="private")
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + '-' + self.artist + '-' + self.genre


class Song(models.Model):

    user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    song_visibility = models.CharField(max_length=100, default="private")
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title 

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title','audio_file']


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

music/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import logout
from django.http import JsonResponse,HttpResponseRedirect
from django.db.models import Q
from django.urls import reverse
from .models import Album, Song
from .forms import AlbumForm, SongForm, UserForm


AUDIO_FILE_TYPES = ['wav', 'mp3']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def index(request, filter_by='all', modifier='private'):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        if modifier == 'private':
            albums = Album.objects.filter(user=request.user)
            song_results = Song.objects.filter(user=request.user)
            query = request.GET.get("q")
            if query:
                albums = albums.filter(
                    Q(album_title__icontains=query) |
                    Q(artist__icontains=query)
                ).distinct()
                song_results = song_results.filter(
                    Q(song_title__icontains=query)
                ).distinct()
                return render(request, 'music/index.html', {
                    'albums': albums,
                    'songs': song_results,
                    'filter_by':filter_by, 
                    'modifier':modifier
                })
            elif filter_by == "favorites":
                albums = albums.filter(is_favorite=True)
                return render(request, 'music/index.html', {'albums': albums, 'filter_by':filter_by, 'modifier':modifier})
            else:
                return render(request, 'music/index.html', {'albums': albums, 'filter_by':filter_by, 'modifier':modifier})
        else:
            albums = Album.objects.filter(album_visibility="public")
            return render(request, 'music/index.html', {'albums': albums, 'filter_by':filter_by, 'modifier':modifier})


def login_user(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            albums = Album.objects.filter(user=request.user)
            return render(request,'music/index.html',{'albums': albums, 'filter_by':'all', 'modifier':'private'})

        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def logout_user(request):

    logout(request)
    return render(request, 'music/login.html')


def register(request):

    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums, 'filter_by':'all', 'modifier':'private'})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)


def detail(request, album_id):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        user = request.user
        albums = Album.objects.filter(user=request.user)
        try:
            album = get_object_or_404(albums, pk=album_id)
            return render(request, 'music/detail.html', {'album': album, 'albums':albums, 'user': user})
        except:
            album = get_object_or_404(Album, pk=album_id)
            if album.album_visibility == 'public':
                return render(request, 'music/detail.html', {'album': album, 'albums':albums, 'user': 'public_user'})
            return JsonResponse({'Error':'Not allowed'})       


def songs(request, filter_by, modifier='private'):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        if modifier == 'private':
            album = Album.objects.filter(user=request.user)
            songs = Song.objects.filter(user=request.user)
            if filter_by == 'favorites':
                songs = songs.filter(is_favorite=True)
            return render(request, 'music/songs.html', {'song_list':songs, 'filter_by':filter_by, 'modifier':modifier, 'albums':album})
        else:
            songs = Song.objects.filter(song_visibility="public")
            return render(request, 'music/songs.html', {'song_list':songs, 'filter_by':filter_by, 'modifier':modifier})


def create_album(request):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album_image = request.FILES.get('filepath', False) 
            if album_image != False:
                album.album_logo = request.FILES['album_logo']
                file_type = album.album_logo.url.split('.')[-1]
                file_type = file_type.lower()
                if file_type not in IMAGE_FILE_TYPES:
                    context = {
                        'album': album,
                        'form': form,
                        'error_message': 'The image must be PNG, JPG or JPEG'
                    }
                    return render(request, 'music/create_album.html', context)
            album.save()
            return render(request,'music/detail.html',{'album': album})
    context = {
        "form": form
    }
    return render(request, 'music/create_album.html', context)


def create_song(request, album_id):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        form = SongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(Album.objects.filter(user=request.user), pk=album_id)
        if form.is_valid():
            albums_songs = album.song_set.all()
            for s in albums_songs:
                if s.song_title == form.cleaned_data.get("song_title"):
                    context = {
                        'album': album,
                        'form': form,
                        'error_message': 'You already added that song',
                    }
                    return render(request, 'music/create_song.html', context)
            song = form.save(commit=False)
            song.user = request.user
            song.album = album
            song.audio_file = request.FILES['audio_file']
            file_type = song.audio_file.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Audio file must be WAV, MP3, or OGG',
                }
                return render(request, 'music/create_song.html', context)

            song.save()
            return render(request, 'music/detail.html', {'album': album})
        context = {
            'album': album,
            'form': form,
        }
        return render(request, 'music/create_song.html', context)


def add_song(request):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        form = SongForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            song = form.save(commit=False)
            song.user = request.user
            song.audio_file = request.FILES['audio_file']
            file_type = song.audio_file.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    'form': form,
                    'error_message': 'Audio file must be WAV, MP3, or OGG',
                }
                return render(request, 'music/add_song.html', context)
            song.save()
            return HttpResponseRedirect(reverse('music:songs',args=('all','private',)))
        context = {
            'form': form,
        }
        return render(request, 'music/add_song.html', context)


def favorite(request, song_id):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        try:
            song = get_object_or_404(Song.objects.filter(user=request.user), pk=song_id)
            if song.is_favorite:
                song.is_favorite = False
            else:
                song.is_favorite = True
            song.save()
        except (KeyError, Song.DoesNotExist):
            return JsonResponse('Song does not exist')
        else:
            return HttpResponseRedirect(reverse('music:songs',args=('all','private',)))


def favorite_album(request, album_id):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        album = get_object_or_404(Album.objects.filter(user=request.user), pk=album_id)
        try:
            if album.is_favorite:
                album.is_favorite = False
            else:
                album.is_favorite = True
            album.save()
        except (KeyError, Album.DoesNotExist):
            return JsonResponse('Album does not exist')
        else:
            return HttpResponseRedirect(reverse('music:index',args=('all','private',)))


def album_modify(request, album_id, modifier):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        album = get_object_or_404(Album.objects.filter(user=request.user), pk=album_id) 

music/templates/music/detail.html
{% extends 'music/layout.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.artist }}</h1>
                    <p class="album-title">{{ album.album_title }}</p>
                    <h6 class="genre">{{ album.genre }}</h6>
                </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                {% if user != 'public_user' %}
                <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
                {% endif %}
                <li role="presentation"><a href="#" onclick="sortTable()">Sort aplhabatically</a></li>
            </ul>

            <script>
                function sortTable() {
                  var table, rows, switching, i, x, y, shouldSwitch;
                  table = document.getElementById("songs_table");
                  switching = true;
                  while (switching) {
                    switching = false;
                    rows = table.rows;
                    for (i = 1; i < (rows.length - 1); i++) {
                      shouldSwitch = false;
                      x = rows[i].getElementsByTagName("TD")[0];
                      y = rows[i + 1].getElementsByTagName("TD")[0];
                      if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                      }
                    }
                    if (shouldSwitch) {
                      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                      switching = true;
                    }
                  }
                }
                </script>
                

            <div class="panel panel-default">
                <div class="table-responsive">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table id="songs_table" class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            {% if user != 'public_user' %}
                            <th>Favorite</th>
                            <th>Actions</th>
                            <th>Move songs</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                {% if user != 'public_user' %}
                                <td>
                                    <center>
                                    <a href="{% url 'music:favorite' song.id %}" class="{% if song.is_favorite %} glyphicon glyphicon-star {% else %} glyphicon glyphicon-star-empty {% endif %}"></a>
                                    </center>
                                </td>
                                <td>
                                    <form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Move song
                                        <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                          <li class="dropdown-submenu">
                                            <a class="test" tabindex="-1" href="#">Move song to album<span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                {% if albums %}
                                                    {% for album in albums %}
                                                        <li><a tabindex="-1" href="{% url 'music:move_song' song.id album.album_title %}">{{ album.album_title }}</a></li>
                                                    {% endfor %}
                                                {% endif %}
                                            </ul>
                                          </li>
                                          <li class="dropdown-submenu">
                                            <a class="test" tabindex="-1" href="#">Copy to album<span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                {% if albums %}
                                                    {% for album in albums %}
                                                        <li><a tabindex="-1" href="{% url 'music:copy_song' song.id album.album_title %}">{{ album.album_title }}</a></li>
                                                    {% endfor %}
                                                {% endif %}
                                            </ul>
                                        </ul>
                                    </div>
                                    
                                    <script>
                                    $(document).ready(function(){
                                      $('.dropdown-submenu a.test').on("click", function(e){
                                        $(this).next('ul').toggle();
                                        e.stopPropagation();
                                        e.preventDefault();
                                      });
                                    });
                                    </script>

                                </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/songs.html
{% extends 'music/layout.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if modifier == 'private' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' 'private' %}">Private songs</a></li>
                <li role="presentation" {% if modifier == 'public' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' 'public' %}">Public songs</a></li>
            </ul>

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' 'private' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:songs' 'favorites' 'private' %}">Favorites</a></li>
                <li role="presentation"><a href="#" onclick="sortTable()">Sort aplhabatically</a></li>
            </ul>

            <script>
                function sortTable() {
                  var table, rows, switching, i, x, y, shouldSwitch;
                  table = document.getElementById("songs_table");
                  switching = true;
                  while (switching) {
                    switching = false;
                    rows = table.rows;
                    for (i = 1; i < (rows.length - 1); i++) {
                      shouldSwitch = false;
                      x = rows[i].getElementsByTagName("TD")[0];
                      y = rows[i + 1].getElementsByTagName("TD")[0];
                      if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                      }
                    }
                    if (shouldSwitch) {
                      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                      switching = true;
                    }
                  }
                }
                </script>

            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="table-responsive">
                    <table id="songs_table" class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Audio File</th>
                                {% if modifier == 'private' %}
                                <th>Album</th>
                                <th>Favorite</th>
                                <th>Visibility</th>
                                <th>Actions</th>
                                <th>Move song</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    {% if modifier == 'private' %}
                                    {% if song.album.id %}
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    {% else %}
                                    <td> None </td>
                                    {% endif %}
                                    <td>
                                        <center>
                                        <a href="{% url 'music:favorite' song.id %}" class="{% if song.is_favorite %} glyphicon glyphicon-star {% else %} glyphicon glyphicon-star-empty {% endif %}"></a>
                                        </center>
                                    </td>
                                    <td>
                                        <ul class="nav nav-pills" style="margin-bottom: 10px;">
                                            <li role="presentation" {% if song.song_visibility == 'private' %}class="active"{% endif %}><a href="{% url 'music:song_modify' song.id 'private' %}">Private</a></li>
                                            <li role="presentation" {% if song.song_visibility == 'public' %}class="active"{% endif %}><a href="{% url 'music:song_modify' song.id 'public' %}">Public</a></li>
                                        </ul>
                                    </td>
                                    {% if modifier == "private" %}
                                    <td>
                                        <form action="{% if song.album.id %} {% url 'music:delete_song' song.album.id song.id %} {% else %} {% url 'music:del_song' song.id %} {% endif %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="album_id" value="{{ song.id }}" />
                                            <button type="submit" class="btn btn-default btn-sm">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </form>
                                    </td>
                                    {% else %}
                                    <td> None </td>
                                    {% endif %}
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"> Move song
                                            <span class="caret"></span></button>
                                            <ul class="dropdown-menu">
                                              <li class="dropdown-submenu">
                                                <a class="test" tabindex="-1" href="#">Move song to album<span class="caret"></span></a>
                                                <ul class="dropdown-menu">
                                                    {% if albums %}
                                                        {% for album in albums %}
                                                            <li><a tabindex="-1" href="{% url 'music:move_song' song.id album.album_title %}">{{ album.album_title }}</a></li>
                                                        {% endfor %}
                                                    {% endif %}
                                                </ul>
                                              </li>
                                              <li class="dropdown-submenu">
                                                <a class="test" tabindex="-1" href="#">Copy to album<span class="caret"></span></a>
                                                <ul class="dropdown-menu">
                                                    {% if albums %}
                                                        {% for album in albums %}
                                                            <li><a tabindex="-1" href="{% url 'music:copy_song' song.id album.album_title %}">{{ album.album_title }}</a></li>
                                                        {% endfor %}
                                                    {% endif %}
                                                </ul>
                                            </ul>
                                        </div>
                                        
                                        <script>
                                        $(document).ready(function(){
                                          $('.dropdown-submenu a.test').on("click", function(e){
                                            $(this).next('ul').toggle();
                                            e.stopPropagation();
                                            e.preventDefault();
                                          });
                                        });
                                        </script>
    
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}